### ISSUE TITLE
About train

### ISSUE THREAD

**Issue by liuxunfu** [dumyy/handpose#1]
hi,
thanks for sharing your project, I have one question here：
    Can this project train ICVL data sets? How to train?

**Comment by dumyy** [comment]
Thanks for your attention.
This is just an example for nyu dataset.  We will update the source codes of three datasets after the paper is available.

**Comment by liuxunfu** [comment]
> Thanks for your attention.
> This is just an example for nyu dataset. We will update the source codes of three datasets after the paper is available.

Thanks for your reply. Okay, thank you.

**Comment by kazucmpt** [comment]
When will it be available?
I would like to train the model by ICVL data sets.
Would you upload the training source codes of ICVL data set?
Now we can access to the paper.
