### ISSUE TITLE
Code_workflow

### ISSUE THREAD

**Issue by ibrahimrazu** [dumyy/handpose#12]
Hi, Thanks again for sharing your code. I was going through your codebase and got confused on the following. Could share your view on those?

1. In the NYU train_and_test.py script, what is the purpose of declaring cubes(250,250,250)? Are those denoting correspondence to depth map?
2. In the same script, where did you compute initial feature extraction value, T? Was it Basenet2 in Basemodel module? Because,  I'm planning to use the block for 48 by 48 input along with 96 by 96 to concatenate T feature maps.

**Comment by MedlarTea** [comment]
Hi, Md Ibrahim Khalil! It looks like you you have successfully implemented the code. I'm a novice. I'm confused abount the code in line 999 in /directory/data/importers.py. The train_NYU.txt file do not exit in  NYUdataset/train/. How can I get it? Thanks a lot!!!

**Comment by ibrahimrazu** [comment]
Hi Medlar, they’ve used v2v posenet pre-computed centers. So you just need to copy and put those as txt files into train and test subfolders. Detailed description is given here: 
cache/NYU/readme.md

**Comment by MedlarTea** [comment]
Oh! Thanks Thanks Thanks!!!

**Comment by dumyy** [comment]
1. cude is a bounding box to crop the hand area in the 3D space. we use the 
box(250mm,250mm,250mm) when testing.
2. initial featue T:  hand3_map_ = global_fms[-3]  feature size (12, 12), in the line 62 of basemodel

**Comment by ibrahimrazu** [comment]
Thanks a lot 🙂

**Comment by ibrahimrazu** [comment]
![2847B183-3216-4B93-8AB0-398A228E3A83](https://user-images.githubusercontent.com/15684976/63138002-a0841d80-bfa6-11e9-8335-62b9ccdb215d.jpeg)
Hi i have another question, 
For the NYU dataset, while loading that, you did not use the separated ‘r’ channels. 
Is there any reason?
