### ISSUE TITLE
About Gesture Segmentation

### ISSUE THREAD

**Issue by liuxunfu** [dumyy/handpose#13]
Hi, thank you for your repo. I have two questions to ask you.
    1 Is your gesture segmentation based on the depth threshold?
    2 Where to set the depth threshold?

**Comment by dumyy** [comment]
center of mass

**Comment by dumyy** [comment]
ues a com to set a bounding box in 3D space then map it to the image, and crop the hand.

**Comment by liuxunfu** [comment]
> ues a com to set a bounding box in 3D space then map it to the image, and crop the hand.

Ok, thank you. Which script is the relevant settings in?

**Comment by dumyy** [comment]
[script](https://github.com/dumyy/handpose/blob/master/data/importers.py)
such as NYU dataset, from line 995 to 1084. 
what's more, please refer to data reprocess in readme.

**Comment by liuxunfu** [comment]
> [script](https://github.com/dumyy/handpose/blob/master/data/importers.py)
> such as NYU dataset, from line 995 to 1084.
> what's more, please refer to data reprocess in readme.

Ok, thank you.
