### ISSUE TITLE
Resnet-50 basemodel structure

### ISSUE THREAD

**Issue by ibrahimrazu** [dumyy/handpose#17]
Hi, 
Thanks again for sharing your code. While going through your codebase, i can see that you created some resnet blocks like this:
![resnet-q1](https://user-images.githubusercontent.com/15684976/62222508-7bc26000-b381-11e9-947a-ba9871541529.PNG)
Where base depth is 512 for ''block4'.
But you implemented it in a slightly different way: 
![resnet-q2](https://user-images.githubusercontent.com/15684976/62222602-a44a5a00-b381-11e9-9c08-7844731cf061.PNG)
Last 2 blocks have 64*4 each if i am correct. Is there a reason behind that?

**Comment by dumyy** [comment]
in fact, the input is only a depth map, so it's easier compared to other tasks. Here we simply the resnet, and make its end channel only 256, and of course it's enough.

**Comment by ibrahimrazu** [comment]
Got it! Thanks a lot :-) 
Now i realize why you never needed to use a deeper resnet
