### ISSUE TITLE
Variable crop_joint_idx ?

### ISSUE THREAD

**Issue by ghost** [dumyy/handpose#19]
Hi
Thanks a lot for the code. Can you tell what information crop_joint_idx variable in the file data/importer.py represents ? It is being used as an index and the gtorig[crop_joint_idx ] is passed as center of mass, but how is this crop_joint_idx index decided/chosen ?

-Sidharth.

**Comment by dumyy** [comment]
mcp joint
you can refer to the articles :
[deepprior++](https://arxiv.org/pdf/1708.08325.pdf)
[v2v](http://openaccess.thecvf.com/content_cvpr_2018/papers/Moon_V2V-PoseNet_Voxel-to-Voxel_Prediction_CVPR_2018_paper.pdf)
