### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by huangshaoguang** [dumyy/handpose#2]
Hello！Thank you for your share very much! When I train the model（run train_and_test.py） I come with a problem: 
File "../..\data\importers.py", line 1000, in loadSequence
    f = open(comlabels, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'E:/nyu_hand_dataset_v2/dataset//train_NYU.txt'

How to solve it?

**Comment by dumyy** [comment]
@huangshaoguang 'train_NYU.txt'  is the com centers we used, which can be got from [https://cv.snu.ac.kr/research/V2V-PoseNet/NYU/center/center_train_refined.txt](url)

**Comment by dumyy** [comment]
Of course, test_NYU.txt is the com centers of test dataset, which can be got from [https://github.com/mks0601/V2V-PoseNet_RELEASE](url) by the same way

**Comment by huangshaoguang** [comment]
OK! I am training it, Thank you very much!
