### ISSUE TITLE
Question about differences in accuracy of real-time demo

### ISSUE THREAD

**Issue by eunmipark-dev** [dumyy/handpose#21]
Hi,  Thanks for sharing great code.
I have a question about a real-time demo.

I used your training source, trained on NYU and MSRA datasets to get a model.
I ran a real-time demo using the model I got and it's much less accurate than the demo video on your project page.

Can you tell me what dataset you trained on the project demo video?

* Video Link
https://blog.naver.com/lordged/221673755880
* Camera : Intel RealSense Depth Camera D435
* The model using MSRA is more accurate than the model using NYU, so I only uploaded video using MSRA.

**Comment by baifei2018** [comment]
Hi,dear eunmipark1! It looks like you you have successfully implemented the code on  on MSRA datasets. I meet this problem when i run MSRA/train_and_test.py,could you please help me with it ?
thank you so much!!!!!
/media/cv/Project/bf/CrossInfoNet/network/MSRA/train_and_test.py
Loading cache data from ../../cache/MSRA//MSRA15Importer_P0_None_com_200_cache.pkl
Shuffling
Loading cache data from ../../cache/MSRA//MSRA15Importer_P1_None_com_200_cache.pkl
Shuffling
Loading cache data from ../../cache/MSRA//MSRA15Importer_P2_None_com_200_cache.pkl
Shuffling
Loading cache data from ../../cache/MSRA//MSRA15Importer_P3_None_com_180_cache.pkl
Shuffling
Loading cache data from ../../cache/MSRA//MSRA15Importer_P4_None_com_180_cache.pkl
Shuffling
Loading cache data from ../../cache/MSRA//MSRA15Importer_P5_None_com_180_cache.pkl
Shuffling
Loading cache data from ../../cache/MSRA//MSRA15Importer_P6_None_com_170_cache.pkl
Shuffling
Loading cache data from ../../cache/MSRA//MSRA15Importer_P7_None_com_160_cache.pkl
Shuffling
Loading cache data from ../../cache/MSRA//MSRA15Importer_P8_None_com_150_cache.pkl
Traceback (most recent call last):
File "/media/cv/Project/bf/CrossInfoNet/network/MSRA/train_and_test.py", line 36, in 
Seq_test_raw = Seq_all.pop(MID)
TypeError: 'NoneType' object cannot be interpreted as an integer
Shuffling

**Comment by eunmipark-dev** [comment]
> Hi,dear eunmipark1! It looks like you you have successfully implemented the code on on MSRA datasets. I meet this problem when i run MSRA/train_and_test.py,could you please help me with it ?
> thank you so much!!!!!
> /media/cv/Project/bf/CrossInfoNet/network/MSRA/train_and_test.py
> Loading cache data from ../../cache/MSRA//MSRA15Importer_P0_None_com_200_cache.pkl
> Shuffling
> Loading cache data from ../../cache/MSRA//MSRA15Importer_P1_None_com_200_cache.pkl
> Shuffling
> Loading cache data from ../../cache/MSRA//MSRA15Importer_P2_None_com_200_cache.pkl
> Shuffling
> Loading cache data from ../../cache/MSRA//MSRA15Importer_P3_None_com_180_cache.pkl
> Shuffling
> Loading cache data from ../../cache/MSRA//MSRA15Importer_P4_None_com_180_cache.pkl
> Shuffling
> Loading cache data from ../../cache/MSRA//MSRA15Importer_P5_None_com_180_cache.pkl
> Shuffling
> Loading cache data from ../../cache/MSRA//MSRA15Importer_P6_None_com_170_cache.pkl
> Shuffling
> Loading cache data from ../../cache/MSRA//MSRA15Importer_P7_None_com_160_cache.pkl
> Shuffling
> Loading cache data from ../../cache/MSRA//MSRA15Importer_P8_None_com_150_cache.pkl
> Traceback (most recent call last):
> File "/media/cv/Project/bf/CrossInfoNet/network/MSRA/train_and_test.py", line 36, in
> Seq_test_raw = Seq_all.pop(MID)
> TypeError: 'NoneType' object cannot be interpreted as an integer
> Shuffling

Try this line
/media/cv/Project/bf/CrossInfoNet/network/MSRA/train_and_test.py --dataset msra

**Comment by baifei2018** [comment]
These files have been generated in these "caches / MSRA / "folder, and the MSRA dataset seemed to be puted into. But these files are from 200~150, is it that I didn't feed it completely~ Would you please send me the complete MSRA dataset and NYU dataset for me? My email is baifei@whut.edu.cn, thank you very much for your help~
This is the name of the file I generated and looks like a partial duplication.
MSRA15Importer_P0_None_com_200_cache.pkl
MSRA15Importer_P0_None_com_180_cache.pkl
MSRA15Importer_P0_None_com_170_cache.pkl
MSRA15Importer_P0_None_com_160_cache.pkl
MSRA15Importer_P0_None_com_150_cache.pkl

**Comment by dumyy** [comment]
BIGHAND dataset
It should be the best dataset  for real-time demo

**Comment by dumyy** [comment]
And have you changed the camera info of yours in the  72 of real-time demo?
`
set your camera info here
 di = DepthImporter(fx=475.268, fy=flag*475.268, ux=313.821, uy=246.075)

`
