### ISSUE TITLE
Question about MSRA

### ISSUE THREAD

**Issue by baifei2018** [dumyy/handpose#22]
Hi, thanks a lot  for your awesome work!
I meet this problem when i run MSRA/train_and_test.py,could you please help me with it ?
thank you so much!!!!!
/media/cv/Project/bf/CrossInfoNet/network/MSRA/train_and_test.py
Loading cache data from ../../cache/MSRA//MSRA15Importer_P0_None_com_200_cache.pkl
Shuffling
Loading cache data from ../../cache/MSRA//MSRA15Importer_P1_None_com_200_cache.pkl
Shuffling
Loading cache data from ../../cache/MSRA//MSRA15Importer_P2_None_com_200_cache.pkl
Shuffling
Loading cache data from ../../cache/MSRA//MSRA15Importer_P3_None_com_180_cache.pkl
Shuffling
Loading cache data from ../../cache/MSRA//MSRA15Importer_P4_None_com_180_cache.pkl
Shuffling
Loading cache data from ../../cache/MSRA//MSRA15Importer_P5_None_com_180_cache.pkl
Shuffling
Loading cache data from ../../cache/MSRA//MSRA15Importer_P6_None_com_170_cache.pkl
Shuffling
Loading cache data from ../../cache/MSRA//MSRA15Importer_P7_None_com_160_cache.pkl
Shuffling
Loading cache data from ../../cache/MSRA//MSRA15Importer_P8_None_com_150_cache.pkl
Traceback (most recent call last):
  File "/media/cv/Project/bf/CrossInfoNet/network/MSRA/train_and_test.py", line 36, in <module>
    Seq_test_raw = Seq_all.pop(MID)
TypeError: 'NoneType' object cannot be interpreted as an integer
Shuffling

**Comment by dumyy** [comment]
```
train:  python train_and_test.py --test-sub ${sub-num}
test:   python test_msra.py --test-sub ${sub-num}
ex:
python python train_and_test.py --test-sub 3
python test_msra.py --test-sub 3

```
you should set the subject you are testing

**Comment by baifei2018** [comment]
I solved this problem according to the method you said~ thank you very much for your help！！

**Comment by weilanShi** [comment]
> I solved this problem according to the method you said~ thank you very much for your help！！

hello,  could you share the  MSRA datasets or the link of MSRA ?  Thank you very much for your help！！
