### ISSUE TITLE
MSRA crop

### ISSUE THREAD

**Issue by cheolhwanyoo** [dumyy/handpose#3]
Thank you very much for sharing your project! 

When I trained msra using depth thresholding or pretrained com from v2v-posenet, performance was not good as I expected .

I want to know how you get the com in msra dataset.

Thank you.

**Comment by dumyy** [comment]
@cheolhwanyoo  I have updated the MRSA train and test code.
There are some tips, hope that can help you.
1. MSRA dataset has 2 versions. We used the order while the v2v-posenet used the new. So we didn't use its com. Here we use a  com （center of mass） calculated by the depth map samed as deep-prior.
2. In the data preprocessing, we use a dynamic bounding box to crop the training dataset , while testing, we use a rigid size of (175,175,175) to deal with different subject's hand sizes. You can find them in the `data/importers.py/`
3. For the online data augment, change the camera info (fx,fy,cx,cz) .

**Comment by cheolhwanyoo** [comment]
Thank you very much for your kind answers!!
I'll try it again!
