### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by eparvizi** [dumyy/handpose#7]
Thanks so much for sharing your work! Could you please provide a link to download the pre-trained models for the datasets you used in your network (HANDS 17, ICVL, NYU and MSRA)? Thanks a lot!

**Comment by dumyy** [comment]
the network is trained beginning with that all weights  initialized from the zero-mean normal
distribution. So the 'pred-trained' models you said mean?

**Comment by eparvizi** [comment]
Sorry I wasn't clear. I meant the model weights output by your network, for us to use as pretrained models.

**Comment by dumyy** [comment]
I got it, but you can train the model yourself with the provide code and use the current weights as the pretrained model for the next stage.
I will upload the trained-models as soon as possible

**Comment by eparvizi** [comment]
I appreciate it! It helps to speed up evaluating. Please update when the uploads are available, thank you!

**Comment by eparvizi** [comment]
Hi there! When can we expect the trained models to be uploaded? Thanks!

**Comment by eparvizi** [comment]
Could you provide a link to the trained models please?

**Comment by kazucmpt** [comment]
I need trained model, too. Would you upload it?

**Comment by danioj5** [comment]
Hi,
could you please share a trained model to be able to directly use the demo without previous training? I need it urgently to generate reliable annotations for my own images, and it would be great to be able to use your model. Thanks in advance!

**Comment by eparvizi** [comment]
Hello @dumyy, could you please share the trained models with us? Thanks!
